Add color customization with Dualbandwidth support
ddrown/omnia-led-colors pull request #8
Opened 2020-09-19 23:14 UTC by rll-rll

This work expands chall8908's work and adds color customization to dualbandwidth mode.
+config update to work on Turris Omnia 2019+

2020-09-20 23:10 UTC, ddrown requested changes
The rest of this code looks fine, just need a change to the install script

2020-09-20 23:10 UTC, ddrown commented on install
> +[ /etc/config/omnia-led-colors -nt omnia-led-colors.config ] || cp omnia-led-colors.config /etc/config/omnia-led-colors
I don't want this to overwrite someone's customized configuration, only set the defaults if there's no configuration

2020-09-24 07:05 UTC, rll-rll commented on install
> +[ /etc/config/omnia-led-colors -nt omnia-led-colors.config ] || cp omnia-led-colors.config /etc/config/omnia-led-colors
Reverted commit 0749d99be438f5d1ee8c3430761312e36cedb9a5

2020-09-26 22:56 UTC, merged

2020-09-26 22:57 UTC, ddrown commented
Thanks for the PR!